// Generator/AcceptMethodGenerator.cs
using System.Text;
using Old8Lang.CodeGen.Scanner;

namespace Old8Lang.CodeGen.Generator;

/// <summary>
/// Accept 方法生成器
/// </summary>
public class AcceptMethodGenerator
{
    private readonly List<AstNodeInfo> _nodes;

    public AcceptMethodGenerator(List<AstNodeInfo> nodes)
    {
        _nodes = nodes;
    }

    /// <summary>
    /// 为所有节点生成 Accept 方法
    /// </summary>
    /// <returns>文件名 -> 代码内容的字典</returns>
    public Dictionary<string, string> GenerateAll()
    {
        var result = new Dictionary<string, string>();

        foreach (var node in _nodes)
        {
            var code = GenerateForNode(node);
            var fileName = $"{node.ClassName}.Accept.generated.cs";
            result[fileName] = code;
        }

        return result;
    }

    /// <summary>
    /// 为单个节点生成 Accept 方法
    /// </summary>
    private string GenerateForNode(AstNodeInfo node)
    {
        var sb = new StringBuilder();

        // 文件头
        AppendFileHeader(sb, node);

        // Using 语句
        sb.AppendLine("using Old8Lang.AST.Visitor;");
        sb.AppendLine();

        // 命名空间
        sb.AppendLine($"namespace {node.Namespace};");
        sb.AppendLine();

        // 类声明（partial）
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {node.ClassName} 的 Accept 方法实现（自动生成）");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class {node.ClassName}");
        sb.AppendLine("{");

        // Accept 方法
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 接受 Visitor 访问");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override TResult Accept<TResult>(IVisitor<TResult> visitor)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return visitor.Visit{node.ClassName}(this);");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void AppendFileHeader(StringBuilder sb, AstNodeInfo node)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// 此文件由代码生成器自动生成，请勿手动修改");
        sb.AppendLine($"// 生成时间：{DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"// 节点：{node.ClassName}");
        sb.AppendLine();
    }
}
