// Generator/VisitorImplementationGenerator.cs
using System.Text;
using Old8Lang.CodeGen.Scanner;

namespace Old8Lang.CodeGen.Generator;

/// <summary>
/// Visitor 实现骨架生成器
/// 生成 InterpreterVisitor, CompilerVisitor, TypeInferenceVisitor 的方法骨架
/// </summary>
public class VisitorImplementationGenerator
{
    private readonly List<AstNodeInfo> _nodes;

    public VisitorImplementationGenerator(List<AstNodeInfo> nodes)
    {
        _nodes = nodes;
    }

    /// <summary>
    /// 生成 InterpreterVisitor 的骨架
    /// </summary>
    public string GenerateInterpreterStubs()
    {
        var sb = new StringBuilder();

        AppendFileHeader(sb, "InterpreterVisitor");
        AppendUsings(sb, isInterpreter: true);

        sb.AppendLine("namespace Old8Lang.AST.Visitor;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// InterpreterVisitor - 所有节点的访问方法（自动生成的骨架）");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public partial class InterpreterVisitor");
        sb.AppendLine("{");

        foreach (var node in _nodes.OrderBy(n => n.Category).ThenBy(n => n.ClassName))
        {
            AppendInterpreterVisitMethod(sb, node);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// 生成 CompilerVisitor 的骨架
    /// </summary>
    public string GenerateCompilerStubs()
    {
        var sb = new StringBuilder();

        AppendFileHeader(sb, "CompilerVisitor");
        AppendUsings(sb, isInterpreter: false);

        sb.AppendLine("namespace Old8Lang.AST.Visitor;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// CompilerVisitor - 所有节点的访问方法（自动生成的骨架）");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public partial class CompilerVisitor");
        sb.AppendLine("{");

        foreach (var node in _nodes.OrderBy(n => n.Category).ThenBy(n => n.ClassName))
        {
            AppendCompilerVisitMethod(sb, node);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// 生成 TypeInferenceVisitor 的骨架
    /// </summary>
    public string GenerateTypeInferenceStubs()
    {
        var sb = new StringBuilder();

        AppendFileHeader(sb, "TypeInferenceVisitor");
        AppendUsings(sb, isInterpreter: false);

        sb.AppendLine("namespace Old8Lang.AST.Visitor;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// TypeInferenceVisitor - 所有节点的访问方法（自动生成的骨架）");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public partial class TypeInferenceVisitor");
        sb.AppendLine("{");

        foreach (var node in _nodes.OrderBy(n => n.Category).ThenBy(n => n.ClassName))
        {
            AppendTypeInferenceVisitMethod(sb, node);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private void AppendFileHeader(StringBuilder sb, string visitorName)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// 此文件由代码生成器自动生成 - {visitorName} 方法骨架");
        sb.AppendLine("// 请在实现对应方法后删除此文件中的对应方法，或将其迁移到手动维护的 partial class 文件中");
        sb.AppendLine($"// 生成时间：{DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"// 节点数量：{_nodes.Count}");
        sb.AppendLine();
    }

    private void AppendUsings(StringBuilder sb, bool isInterpreter)
    {
        // 完整的 using 语句列表
        sb.AppendLine("using Old8Lang.AST.Expression;");
        sb.AppendLine("using Old8Lang.AST.Expression.AnyValues;");
        sb.AppendLine("using Old8Lang.AST.Expression.Generators;");
        sb.AppendLine("using Old8Lang.AST.Expression.Intermediates;");
        sb.AppendLine("using Old8Lang.AST.Expression.StaticValues;");
        sb.AppendLine("using Old8Lang.AST.Expression.Value;");
        sb.AppendLine("using Old8Lang.AST.Statement;");
        sb.AppendLine();
    }

    private void AppendInterpreterVisitMethod(StringBuilder sb, AstNodeInfo node)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 访问 {node.ClassName} 节点（解释器）");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public LangValueType Visit{node.ClassName}({node.ClassName} node)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        // TODO: 迁移自 {node.ClassName}.Run()");
        sb.AppendLine($"        throw new NotImplementedException(\"Visit{node.ClassName} 尚未实现\");");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    private void AppendCompilerVisitMethod(StringBuilder sb, AstNodeInfo node)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 访问 {node.ClassName} 节点（编译器）");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public object? Visit{node.ClassName}({node.ClassName} node)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        // TODO: 迁移自 {node.ClassName}.GenerateIl()");
        sb.AppendLine($"        throw new NotImplementedException(\"Visit{node.ClassName} 尚未实现\");");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    private void AppendTypeInferenceVisitMethod(StringBuilder sb, AstNodeInfo node)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 推断 {node.ClassName} 节点的类型");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public Type? Visit{node.ClassName}({node.ClassName} node)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        // TODO: 迁移自 {node.ClassName}.OutputType()");
        sb.AppendLine($"        return typeof(object); // 默认返回 object 类型");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }
}
