// Generator/VisitorInterfaceGenerator.cs
using System.Text;
using Old8Lang.CodeGen.Scanner;

namespace Old8Lang.CodeGen.Generator;

/// <summary>
/// IVisitor 接口生成器
/// </summary>
public class VisitorInterfaceGenerator
{
    private readonly List<AstNodeInfo> _nodes;

    public VisitorInterfaceGenerator(List<AstNodeInfo> nodes)
    {
        _nodes = nodes;
    }

    /// <summary>
    /// 生成 IVisitor 接口代码
    /// </summary>
    public string Generate()
    {
        var sb = new StringBuilder();

        // 文件头
        AppendFileHeader(sb);

        // Using 语句
        AppendUsings(sb);

        // 命名空间
        sb.AppendLine("namespace Old8Lang.AST.Visitor;");
        sb.AppendLine();

        // 接口声明
        AppendInterfaceDeclaration(sb);

        return sb.ToString();
    }

    private void AppendFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// 此文件由代码生成器自动生成，请勿手动修改");
        sb.AppendLine($"// 生成时间：{DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"// 节点数量：{_nodes.Count}");
        sb.AppendLine();
    }

    private void AppendUsings(StringBuilder sb)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using Old8Lang.AST.Expression;");
        sb.AppendLine("using Old8Lang.AST.Expression.AnyValues;");
        sb.AppendLine("using Old8Lang.AST.Expression.Generators;");
        sb.AppendLine("using Old8Lang.AST.Expression.Intermediates;");
        sb.AppendLine("using Old8Lang.AST.Expression.StaticValues;");
        sb.AppendLine("using Old8Lang.AST.Expression.Value;");
        sb.AppendLine("using Old8Lang.AST.Statement;");
        sb.AppendLine();
    }

    private void AppendInterfaceDeclaration(StringBuilder sb)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Visitor 模式基础接口");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <typeparam name=\"TResult\">返回结果类型</typeparam>");
        sb.AppendLine("public interface IVisitor<out TResult>");
        sb.AppendLine("{");

        // Statement 节点
        var statements = _nodes
            .Where(n => n.Category == AstNodeCategory.Statement)
            .OrderBy(n => n.ClassName)
            .ToList();

        if (statements.Any())
        {
            sb.AppendLine("    // ===== Statement 访问方法 =====");
            foreach (var node in statements)
            {
                AppendVisitMethod(sb, node);
            }
            sb.AppendLine();
        }

        // Expression 节点
        var expressions = _nodes
            .Where(n => n.Category == AstNodeCategory.Expression)
            .OrderBy(n => n.ClassName)
            .ToList();

        if (expressions.Any())
        {
            sb.AppendLine("    // ===== Expression 访问方法 =====");
            foreach (var node in expressions)
            {
                AppendVisitMethod(sb, node);
            }
            sb.AppendLine();
        }

        // Value 节点
        var values = _nodes
            .Where(n => n.Category == AstNodeCategory.Value)
            .OrderBy(n => n.ClassName)
            .ToList();

        if (values.Any())
        {
            sb.AppendLine("    // ===== Value 访问方法 =====");
            foreach (var node in values)
            {
                AppendVisitMethod(sb, node);
            }
        }

        sb.AppendLine("}");
    }

    private void AppendVisitMethod(StringBuilder sb, AstNodeInfo node)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 访问 {node.ClassName} 节点");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    TResult Visit{node.ClassName}({node.ClassName} node);");
        sb.AppendLine();
    }
}
