<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PreserveCompilationContext>true</PreserveCompilationContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Jint" Version="4.4.2" />
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
        <PackageReference Include="dnlib" Version="4.5.0" />
        <PackageReference Include="pythonnet" Version="3.0.5" />
        <!-- 使用 NuGet 包替代项目引用 -->
        <PackageReference Include="Old8Lang.PackageManager.Core" Version="1.1.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Old8Lang.DatabaseLib\Old8Lang.DatabaseLib.csproj" />
        <ProjectReference Include="..\Old8Lang.MachineLearningLib\Old8Lang.MachineLearningLib.csproj" />
        <ProjectReference Include="..\Old8Lang.SerializationLib\Old8Lang.SerializationLib.csproj" />
        <ProjectReference Include="..\Old8LangLib\Old8LangLib.csproj" />
        <ProjectReference Include="..\Old8Lang.NetLib\Old8Lang.NetLib.csproj" />
    </ItemGroup>

</Project>
